### ISSUE TITLE
Problems with Beta  20211115.1

### ISSUE THREAD

**Issue by rhoddan** [bimmerconnected/ha_custom_component#7]
I run the BETA before this and it worked good. Now with latest - I get following (Europe)... However thanks for an excellent work!

2021-11-15 10:19:33 ERROR (MainThread) [homeassistant.components.lock] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/lock.py", line 93, in update
    result["door_lock_state"] = vehicle_state.door_lock_state.value
AttributeError: 'NoneType' object has no attribute 'value'
2021-11-15 10:19:33 ERROR (MainThread) [homeassistant.components.binary_sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/binary_sensor.py", line 251, in update
    self._attr_is_on = self.entity_description.value_fn(
  File "/config/custom_components/bmw_connected_drive/binary_sensor.py", line 60, in _are_doors_locked
    extra_attributes["door_lock_state"] = vehicle_state.door_lock_state.value
AttributeError: 'NoneType' object has no attribute 'value'
2021-11-15 10:19:33 ERROR (MainThread) [homeassistant.components.binary_sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/binary_sensor.py", line 251, in update
    self._attr_is_on = self.entity_description.value_fn(
  File "/config/custom_components/bmw_connected_drive/binary_sensor.py", line 79, in _are_problems_detected
    for report in vehicle_state.condition_based_services:
TypeError: 'NoneType' object is not iterable
2021-11-15 10:19:33 ERROR (MainThread) [homeassistant.components.sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/sensor.py", line 528, in update
    self._attr_native_value = getattr(vehicle_state, sensor_key).value
AttributeError: 'NoneType' object has no attribute 'value'
2021-11-15 10:19:33 ERROR (MainThread) [homeassistant.components.binary_sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/binary_sensor.py", line 251, in update
    self._attr_is_on = self.entity_description.value_fn(
  File "/config/custom_components/bmw_connected_drive/binary_sensor.py", line 102, in _is_vehicle_charging
    extra_attributes["charging_status"] = vehicle_state.charging_status.value
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by danfulton72** [comment]
When I update to 20211115.1 via HACS the requirement for bimmer_connected drops back to bimmer_connected==0.7.22.

And the version in manifest.json is   "version": "20211110.1"

I think the release isn't tagged properly?

**Comment by rhoddan** [comment]
20311115.2 seems to work again 👍👍

**Comment by jon798** [comment]
I get the following after updating via HACS and restating HA:

Setup failed for bmw_connected_drive: Requirements for bmw_connected_drive not found: ['bimmer_connected==0.8.0.0b7'].

Unable to install package bimmer_connected==0.8.0.0b7: ERROR: Could not find a version that satisfies the requirement bimmer_connected==0.8.0.0b7

Previously the last 202110xxx beta sort of worked - it got charge level for our electric mini and fuel level for our X3, but claimed all the doors and windows were open on both cars and couldn't tell whether the electric mini was plugged in or not.
